[package]
name = "ash-survival-kit"
version = "0.1.0"
authors = ["rotary"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.29.0"
cgmath = "0.17.0"
winit = "0.20.0-alpha2"